packages:
  - 'apps/*'
  - 'configs/*'
  - 'packages/*'
  - 'assets/*'
  - 'services/*'
  - 'backend/*'
  - 'tools/*'
  - 'tests/*'
catalog:
  next: 15.3.8
  '@rjsf/core': ^5.24.12
  '@rjsf/utils': ^5.24.12
  '@rjsf/validator-ajv8': ^5.24.12
  zod: ^4.1.12
  access-zones: 1.0.0
  drizzle-orm: 1.0.0-beta.11-05230d9
  vitest: ^4.0.17
  '@tiptap/core': ^3.17.1
  '@tiptap/pm': ^3.17.1
  '@tiptap/react': ^3.17.1
  '@tiptap/starter-kit': ^3.17.1
  '@tiptap/extension-blockquote': ^3.17.1
  '@tiptap/extension-bubble-menu': ^3.17.1
  '@tiptap/extension-bullet-list': ^3.17.1
  '@tiptap/extension-collaboration': ^3.17.1
  '@tiptap/extension-collaboration-cursor': ^3.0.0
  '@tiptap/extension-heading': ^3.17.1
  '@tiptap/extension-horizontal-rule': ^3.17.1
  '@tiptap/extension-image': ^3.17.1
  '@tiptap/extension-link': ^3.17.1
  '@tiptap/extension-list-item': ^3.17.1
  '@tiptap/extension-ordered-list': ^3.17.1
  '@tiptap/extension-placeholder': ^3.17.1
  '@tiptap/extension-strike': ^3.17.1
  '@tiptap/extension-text-align': ^3.17.1
  '@tiptap/extension-underline': ^3.17.1
  '@tiptap/suggestion': ^3.17.1
