packages:
  - 'apps/*'
  - 'configs/*'
  - 'packages/*'
  - 'assets/*'
  - 'services/*'
  - 'backend/*'
  - 'tools/*'
catalog:
  next: 15.3.8
  '@rjsf/core': ^5.24.12
  '@rjsf/utils': ^5.24.12
  '@rjsf/validator-ajv8': ^5.24.12
  zod: ^4.1.12
  access-zones: 1.0.0
  drizzle-orm: 1.0.0-beta.11-05230d9
  vitest: ^4.0.17
