packages:
  - 'apps/*'
  - 'configs/*'
  - 'packages/*'
  - 'assets/*'
  - 'services/*'
  - 'backend/*'
  - 'tools/*'
catalog:
  next: 15.3.8
  '@rjsf/core': ^5.24.12
  '@rjsf/utils': ^5.24.12
  '@rjsf/validator-ajv8': ^5.24.12
  zod: ^4.1.12
