/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as LocaleMainSplatRouteImport } from './routes/$locale/_main/$';
import { Route as LocaleMainAdminDashboardDecisionsIndexRouteImport } from './routes/$locale/_main/admin/_dashboard/decisions/index';
import { Route as LocaleMainAdminDashboardIndexRouteImport } from './routes/$locale/_main/admin/_dashboard/index';
import { Route as LocaleMainAdminDashboardOrgsIndexRouteImport } from './routes/$locale/_main/admin/_dashboard/orgs/index';
import { Route as LocaleMainAdminDashboardRouteRouteImport } from './routes/$locale/_main/admin/_dashboard/route';
import { Route as LocaleMainAdminDashboardUsersIndexRouteImport } from './routes/$locale/_main/admin/_dashboard/users/index';
import { Route as LocaleMainAdminDecisionsInstanceIdRouteImport } from './routes/$locale/_main/admin/decisions/$instanceId';
import { Route as LocaleMainAdminRouteRouteImport } from './routes/$locale/_main/admin/route';
import { Route as LocaleMainDecisionsIndexRouteImport } from './routes/$locale/_main/decisions/index';
import { Route as LocaleMainIndexRouteImport } from './routes/$locale/_main/index';
import { Route as LocaleMainOrgSlugIndexRouteImport } from './routes/$locale/_main/org/$slug/index';
import { Route as LocaleMainOrgSlugRelationshipsIndexRouteImport } from './routes/$locale/_main/org/$slug/relationships/index';
import { Route as LocaleMainOrgIndexRouteImport } from './routes/$locale/_main/org/index';
import { Route as LocaleMainProfileSlugIndexRouteImport } from './routes/$locale/_main/profile/$slug/index';
import { Route as LocaleMainProfileIndexRouteImport } from './routes/$locale/_main/profile/index';
import { Route as LocaleMainRouteRouteImport } from './routes/$locale/_main/route';
import { Route as LocaleMainSearchIndexRouteImport } from './routes/$locale/_main/search/index';
import { Route as LocaleNoHeaderDecisionsSlugDecisionViewCurrentIndexRouteImport } from './routes/$locale/_noHeader/decisions/$slug/_decisionView/current/index';
import { Route as LocaleNoHeaderDecisionsSlugDecisionViewCurrentOpengraphImageRouteImport } from './routes/$locale/_noHeader/decisions/$slug/_decisionView/current/opengraph-image';
import { Route as LocaleNoHeaderDecisionsSlugDecisionViewIndexRouteImport } from './routes/$locale/_noHeader/decisions/$slug/_decisionView/index';
import { Route as LocaleNoHeaderDecisionsSlugDecisionViewOpengraphImageRouteImport } from './routes/$locale/_noHeader/decisions/$slug/_decisionView/opengraph-image';
import { Route as LocaleNoHeaderDecisionsSlugDecisionViewRouteRouteImport } from './routes/$locale/_noHeader/decisions/$slug/_decisionView/route';
import { Route as LocaleNoHeaderDecisionsSlugAssignmentsProfileIdRouteImport } from './routes/$locale/_noHeader/decisions/$slug/assignments/$profileId';
import { Route as LocaleNoHeaderDecisionsSlugAssignmentsIndexRouteImport } from './routes/$locale/_noHeader/decisions/$slug/assignments/index';
import { Route as LocaleNoHeaderDecisionsSlugEditRouteImport } from './routes/$locale/_noHeader/decisions/$slug/edit';
import { Route as LocaleNoHeaderDecisionsSlugProposalProfileIdEditRouteImport } from './routes/$locale/_noHeader/decisions/$slug/proposal/$profileId/edit';
import { Route as LocaleNoHeaderDecisionsSlugProposalProfileIdIndexRouteImport } from './routes/$locale/_noHeader/decisions/$slug/proposal/$profileId/index';
import { Route as LocaleNoHeaderDecisionsSlugProposalProfileIdInviteRouteImport } from './routes/$locale/_noHeader/decisions/$slug/proposal/$profileId/invite';
import { Route as LocaleNoHeaderDecisionsSlugProposalProfileIdReviewsRouteImport } from './routes/$locale/_noHeader/decisions/$slug/proposal/$profileId/reviews';
import { Route as LocaleNoHeaderDecisionsSlugReviewsReviewIdRouteImport } from './routes/$locale/_noHeader/decisions/$slug/reviews/$reviewId';
import { Route as LocaleNoHeaderDecisionsSlugRouteRouteImport } from './routes/$locale/_noHeader/decisions/$slug/route';
import { Route as LocaleNoHeaderProfileSlugDecisionsIdCurrentRouteImport } from './routes/$locale/_noHeader/profile/$slug/decisions/$id/current';
import { Route as LocaleNoHeaderProfileSlugDecisionsIdIndexRouteImport } from './routes/$locale/_noHeader/profile/$slug/decisions/$id/index';
import { Route as LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdEditRouteImport } from './routes/$locale/_noHeader/profile/$slug/decisions/$id/proposal/$profileId/edit';
import { Route as LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdIndexRouteImport } from './routes/$locale/_noHeader/profile/$slug/decisions/$id/proposal/$profileId/index';
import { Route as LocaleNoHeaderProfileSlugPostsPostIdRouteImport } from './routes/$locale/_noHeader/profile/$slug/posts/$postId';
import { Route as LocaleNoHeaderRouteRouteImport } from './routes/$locale/_noHeader/route';
import { Route as LocaleRouteRouteImport } from './routes/$locale/route';
import { Route as LocaleStartIndexRouteImport } from './routes/$locale/start/index';
import { Route as LocaleStartRouteRouteImport } from './routes/$locale/start/route';
import { Route as rootRouteImport } from './routes/__root';
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback';
import { Route as ApiAuthConfirmRouteImport } from './routes/api/auth/confirm';
import { Route as ApiCspReportRouteImport } from './routes/api/csp-report';
import { Route as ApiEmbedsApiIframeRouteImport } from './routes/api/embeds/api/iframe';
import { Route as ApiEmbedsEmbedDotjsRouteImport } from './routes/api/embeds/embed[.]js';
import { Route as ApiOtelTracesRouteImport } from './routes/api/otel/traces';
import { Route as ApiWaitlistSignupRouteImport } from './routes/api/waitlist-signup';
import { Route as IndexRouteImport } from './routes/index';
import { Route as InfoColumbusAddendumRouteImport } from './routes/info/columbus-addendum';
import { Route as InfoCommunityCommitmentsRouteImport } from './routes/info/community-commitments';
import { Route as InfoPrivacyRouteImport } from './routes/info/privacy';
import { Route as InfoRouteRouteImport } from './routes/info/route';
import { Route as InfoTosRouteImport } from './routes/info/tos';
import { Route as LoginIndexRouteImport } from './routes/login/index';
import { Route as LoginRouteRouteImport } from './routes/login/route';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any);
const InfoRouteRoute = InfoRouteRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const LocaleMainRouteRoute = LocaleMainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => LocaleRouteRoute,
} as any);
const LocaleNoHeaderRouteRoute = LocaleNoHeaderRouteRouteImport.update({
  id: '/_noHeader',
  getParentRoute: () => LocaleRouteRoute,
} as any);
const LocaleStartRouteRoute = LocaleStartRouteRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => LocaleRouteRoute,
} as any);
const ApiCspReportRoute = ApiCspReportRouteImport.update({
  id: '/api/csp-report',
  path: '/api/csp-report',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiWaitlistSignupRoute = ApiWaitlistSignupRouteImport.update({
  id: '/api/waitlist-signup',
  path: '/api/waitlist-signup',
  getParentRoute: () => rootRouteImport,
} as any);
const InfoColumbusAddendumRoute = InfoColumbusAddendumRouteImport.update({
  id: '/columbus-addendum',
  path: '/columbus-addendum',
  getParentRoute: () => InfoRouteRoute,
} as any);
const InfoCommunityCommitmentsRoute =
  InfoCommunityCommitmentsRouteImport.update({
    id: '/community-commitments',
    path: '/community-commitments',
    getParentRoute: () => InfoRouteRoute,
  } as any);
const InfoPrivacyRoute = InfoPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => InfoRouteRoute,
} as any);
const InfoTosRoute = InfoTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => InfoRouteRoute,
} as any);
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any);
const LocaleMainIndexRoute = LocaleMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleMainRouteRoute,
} as any);
const LocaleMainSplatRoute = LocaleMainSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleMainRouteRoute,
} as any);
const LocaleMainAdminRouteRoute = LocaleMainAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleMainRouteRoute,
} as any);
const LocaleStartIndexRoute = LocaleStartIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleStartRouteRoute,
} as any);
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthConfirmRoute = ApiAuthConfirmRouteImport.update({
  id: '/api/auth/confirm',
  path: '/api/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiEmbedsEmbedDotjsRoute = ApiEmbedsEmbedDotjsRouteImport.update({
  id: '/api/embeds/embed.js',
  path: '/api/embeds/embed.js',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiOtelTracesRoute = ApiOtelTracesRouteImport.update({
  id: '/api/otel/traces',
  path: '/api/otel/traces',
  getParentRoute: () => rootRouteImport,
} as any);
const LocaleMainAdminDashboardRouteRoute =
  LocaleMainAdminDashboardRouteRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => LocaleMainAdminRouteRoute,
  } as any);
const LocaleMainDecisionsIndexRoute =
  LocaleMainDecisionsIndexRouteImport.update({
    id: '/decisions/',
    path: '/decisions/',
    getParentRoute: () => LocaleMainRouteRoute,
  } as any);
const LocaleMainOrgIndexRoute = LocaleMainOrgIndexRouteImport.update({
  id: '/org/',
  path: '/org/',
  getParentRoute: () => LocaleMainRouteRoute,
} as any);
const LocaleMainProfileIndexRoute = LocaleMainProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LocaleMainRouteRoute,
} as any);
const LocaleMainSearchIndexRoute = LocaleMainSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => LocaleMainRouteRoute,
} as any);
const LocaleNoHeaderDecisionsSlugRouteRoute =
  LocaleNoHeaderDecisionsSlugRouteRouteImport.update({
    id: '/decisions/$slug',
    path: '/decisions/$slug',
    getParentRoute: () => LocaleNoHeaderRouteRoute,
  } as any);
const ApiEmbedsApiIframeRoute = ApiEmbedsApiIframeRouteImport.update({
  id: '/api/embeds/api/iframe',
  path: '/api/embeds/api/iframe',
  getParentRoute: () => rootRouteImport,
} as any);
const LocaleMainAdminDashboardIndexRoute =
  LocaleMainAdminDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleMainAdminDashboardRouteRoute,
  } as any);
const LocaleMainAdminDecisionsInstanceIdRoute =
  LocaleMainAdminDecisionsInstanceIdRouteImport.update({
    id: '/decisions/$instanceId',
    path: '/decisions/$instanceId',
    getParentRoute: () => LocaleMainAdminRouteRoute,
  } as any);
const LocaleMainOrgSlugIndexRoute = LocaleMainOrgSlugIndexRouteImport.update({
  id: '/org/$slug/',
  path: '/org/$slug/',
  getParentRoute: () => LocaleMainRouteRoute,
} as any);
const LocaleMainProfileSlugIndexRoute =
  LocaleMainProfileSlugIndexRouteImport.update({
    id: '/profile/$slug/',
    path: '/profile/$slug/',
    getParentRoute: () => LocaleMainRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute =
  LocaleNoHeaderDecisionsSlugDecisionViewRouteRouteImport.update({
    id: '/_decisionView',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugEditRoute =
  LocaleNoHeaderDecisionsSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugRouteRoute,
  } as any);
const LocaleMainAdminDashboardDecisionsIndexRoute =
  LocaleMainAdminDashboardDecisionsIndexRouteImport.update({
    id: '/decisions/',
    path: '/decisions/',
    getParentRoute: () => LocaleMainAdminDashboardRouteRoute,
  } as any);
const LocaleMainAdminDashboardOrgsIndexRoute =
  LocaleMainAdminDashboardOrgsIndexRouteImport.update({
    id: '/orgs/',
    path: '/orgs/',
    getParentRoute: () => LocaleMainAdminDashboardRouteRoute,
  } as any);
const LocaleMainAdminDashboardUsersIndexRoute =
  LocaleMainAdminDashboardUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => LocaleMainAdminDashboardRouteRoute,
  } as any);
const LocaleMainOrgSlugRelationshipsIndexRoute =
  LocaleMainOrgSlugRelationshipsIndexRouteImport.update({
    id: '/org/$slug/relationships/',
    path: '/org/$slug/relationships/',
    getParentRoute: () => LocaleMainRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugDecisionViewIndexRoute =
  LocaleNoHeaderDecisionsSlugDecisionViewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugDecisionViewOpengraphImageRoute =
  LocaleNoHeaderDecisionsSlugDecisionViewOpengraphImageRouteImport.update({
    id: '/opengraph-image',
    path: '/opengraph-image',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugAssignmentsIndexRoute =
  LocaleNoHeaderDecisionsSlugAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugAssignmentsProfileIdRoute =
  LocaleNoHeaderDecisionsSlugAssignmentsProfileIdRouteImport.update({
    id: '/assignments/$profileId',
    path: '/assignments/$profileId',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugReviewsReviewIdRoute =
  LocaleNoHeaderDecisionsSlugReviewsReviewIdRouteImport.update({
    id: '/reviews/$reviewId',
    path: '/reviews/$reviewId',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugRouteRoute,
  } as any);
const LocaleNoHeaderProfileSlugPostsPostIdRoute =
  LocaleNoHeaderProfileSlugPostsPostIdRouteImport.update({
    id: '/profile/$slug/posts/$postId',
    path: '/profile/$slug/posts/$postId',
    getParentRoute: () => LocaleNoHeaderRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugDecisionViewCurrentIndexRoute =
  LocaleNoHeaderDecisionsSlugDecisionViewCurrentIndexRouteImport.update({
    id: '/current/',
    path: '/current/',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugDecisionViewCurrentOpengraphImageRoute =
  LocaleNoHeaderDecisionsSlugDecisionViewCurrentOpengraphImageRouteImport.update(
    {
      id: '/current/opengraph-image',
      path: '/current/opengraph-image',
      getParentRoute: () => LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute,
    } as any,
  );
const LocaleNoHeaderDecisionsSlugProposalProfileIdIndexRoute =
  LocaleNoHeaderDecisionsSlugProposalProfileIdIndexRouteImport.update({
    id: '/proposal/$profileId/',
    path: '/proposal/$profileId/',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugProposalProfileIdEditRoute =
  LocaleNoHeaderDecisionsSlugProposalProfileIdEditRouteImport.update({
    id: '/proposal/$profileId/edit',
    path: '/proposal/$profileId/edit',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugProposalProfileIdInviteRoute =
  LocaleNoHeaderDecisionsSlugProposalProfileIdInviteRouteImport.update({
    id: '/proposal/$profileId/invite',
    path: '/proposal/$profileId/invite',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugRouteRoute,
  } as any);
const LocaleNoHeaderDecisionsSlugProposalProfileIdReviewsRoute =
  LocaleNoHeaderDecisionsSlugProposalProfileIdReviewsRouteImport.update({
    id: '/proposal/$profileId/reviews',
    path: '/proposal/$profileId/reviews',
    getParentRoute: () => LocaleNoHeaderDecisionsSlugRouteRoute,
  } as any);
const LocaleNoHeaderProfileSlugDecisionsIdIndexRoute =
  LocaleNoHeaderProfileSlugDecisionsIdIndexRouteImport.update({
    id: '/profile/$slug/decisions/$id/',
    path: '/profile/$slug/decisions/$id/',
    getParentRoute: () => LocaleNoHeaderRouteRoute,
  } as any);
const LocaleNoHeaderProfileSlugDecisionsIdCurrentRoute =
  LocaleNoHeaderProfileSlugDecisionsIdCurrentRouteImport.update({
    id: '/profile/$slug/decisions/$id/current',
    path: '/profile/$slug/decisions/$id/current',
    getParentRoute: () => LocaleNoHeaderRouteRoute,
  } as any);
const LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdIndexRoute =
  LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdIndexRouteImport.update({
    id: '/profile/$slug/decisions/$id/proposal/$profileId/',
    path: '/profile/$slug/decisions/$id/proposal/$profileId/',
    getParentRoute: () => LocaleNoHeaderRouteRoute,
  } as any);
const LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdEditRoute =
  LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdEditRouteImport.update({
    id: '/profile/$slug/decisions/$id/proposal/$profileId/edit',
    path: '/profile/$slug/decisions/$id/proposal/$profileId/edit',
    getParentRoute: () => LocaleNoHeaderRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/$locale': typeof LocaleRouteRouteWithChildren;
  '/info': typeof InfoRouteRouteWithChildren;
  '/login': typeof LoginRouteRouteWithChildren;
  '/$locale/start': typeof LocaleStartRouteRouteWithChildren;
  '/api/csp-report': typeof ApiCspReportRoute;
  '/api/waitlist-signup': typeof ApiWaitlistSignupRoute;
  '/info/columbus-addendum': typeof InfoColumbusAddendumRoute;
  '/info/community-commitments': typeof InfoCommunityCommitmentsRoute;
  '/info/privacy': typeof InfoPrivacyRoute;
  '/info/tos': typeof InfoTosRoute;
  '/login/': typeof LoginIndexRoute;
  '/$locale/admin': typeof LocaleMainAdminRouteRouteWithChildren;
  '/$locale/$': typeof LocaleMainSplatRoute;
  '/api/auth/callback': typeof ApiAuthCallbackRoute;
  '/api/auth/confirm': typeof ApiAuthConfirmRoute;
  '/api/embeds/embed.js': typeof ApiEmbedsEmbedDotjsRoute;
  '/api/otel/traces': typeof ApiOtelTracesRoute;
  '/$locale/': typeof LocaleMainIndexRoute;
  '/$locale/start/': typeof LocaleStartIndexRoute;
  '/$locale/decisions/$slug': typeof LocaleNoHeaderDecisionsSlugRouteRouteWithChildren;
  '/api/embeds/api/iframe': typeof ApiEmbedsApiIframeRoute;
  '/$locale/decisions/': typeof LocaleMainDecisionsIndexRoute;
  '/$locale/org/': typeof LocaleMainOrgIndexRoute;
  '/$locale/profile/': typeof LocaleMainProfileIndexRoute;
  '/$locale/search/': typeof LocaleMainSearchIndexRoute;
  '/$locale/admin/decisions/$instanceId': typeof LocaleMainAdminDecisionsInstanceIdRoute;
  '/$locale/decisions/$slug/edit': typeof LocaleNoHeaderDecisionsSlugEditRoute;
  '/$locale/admin/': typeof LocaleMainAdminDashboardIndexRoute;
  '/$locale/org/$slug/': typeof LocaleMainOrgSlugIndexRoute;
  '/$locale/profile/$slug/': typeof LocaleMainProfileSlugIndexRoute;
  '/$locale/decisions/$slug/opengraph-image': typeof LocaleNoHeaderDecisionsSlugDecisionViewOpengraphImageRoute;
  '/$locale/decisions/$slug/assignments/$profileId': typeof LocaleNoHeaderDecisionsSlugAssignmentsProfileIdRoute;
  '/$locale/decisions/$slug/reviews/$reviewId': typeof LocaleNoHeaderDecisionsSlugReviewsReviewIdRoute;
  '/$locale/profile/$slug/posts/$postId': typeof LocaleNoHeaderProfileSlugPostsPostIdRoute;
  '/$locale/admin/decisions/': typeof LocaleMainAdminDashboardDecisionsIndexRoute;
  '/$locale/admin/orgs/': typeof LocaleMainAdminDashboardOrgsIndexRoute;
  '/$locale/admin/users/': typeof LocaleMainAdminDashboardUsersIndexRoute;
  '/$locale/org/$slug/relationships/': typeof LocaleMainOrgSlugRelationshipsIndexRoute;
  '/$locale/decisions/$slug/': typeof LocaleNoHeaderDecisionsSlugDecisionViewIndexRoute;
  '/$locale/decisions/$slug/assignments/': typeof LocaleNoHeaderDecisionsSlugAssignmentsIndexRoute;
  '/$locale/decisions/$slug/current/opengraph-image': typeof LocaleNoHeaderDecisionsSlugDecisionViewCurrentOpengraphImageRoute;
  '/$locale/decisions/$slug/proposal/$profileId/edit': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdEditRoute;
  '/$locale/decisions/$slug/proposal/$profileId/invite': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdInviteRoute;
  '/$locale/decisions/$slug/proposal/$profileId/reviews': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdReviewsRoute;
  '/$locale/profile/$slug/decisions/$id/current': typeof LocaleNoHeaderProfileSlugDecisionsIdCurrentRoute;
  '/$locale/decisions/$slug/current/': typeof LocaleNoHeaderDecisionsSlugDecisionViewCurrentIndexRoute;
  '/$locale/decisions/$slug/proposal/$profileId/': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdIndexRoute;
  '/$locale/profile/$slug/decisions/$id/': typeof LocaleNoHeaderProfileSlugDecisionsIdIndexRoute;
  '/$locale/profile/$slug/decisions/$id/proposal/$profileId/edit': typeof LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdEditRoute;
  '/$locale/profile/$slug/decisions/$id/proposal/$profileId/': typeof LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/$locale': typeof LocaleMainIndexRoute;
  '/info': typeof InfoRouteRouteWithChildren;
  '/api/csp-report': typeof ApiCspReportRoute;
  '/api/waitlist-signup': typeof ApiWaitlistSignupRoute;
  '/info/columbus-addendum': typeof InfoColumbusAddendumRoute;
  '/info/community-commitments': typeof InfoCommunityCommitmentsRoute;
  '/info/privacy': typeof InfoPrivacyRoute;
  '/info/tos': typeof InfoTosRoute;
  '/login': typeof LoginIndexRoute;
  '/$locale/admin': typeof LocaleMainAdminDashboardIndexRoute;
  '/$locale/$': typeof LocaleMainSplatRoute;
  '/api/auth/callback': typeof ApiAuthCallbackRoute;
  '/api/auth/confirm': typeof ApiAuthConfirmRoute;
  '/api/embeds/embed.js': typeof ApiEmbedsEmbedDotjsRoute;
  '/api/otel/traces': typeof ApiOtelTracesRoute;
  '/$locale/start': typeof LocaleStartIndexRoute;
  '/$locale/decisions/$slug': typeof LocaleNoHeaderDecisionsSlugDecisionViewIndexRoute;
  '/api/embeds/api/iframe': typeof ApiEmbedsApiIframeRoute;
  '/$locale/decisions': typeof LocaleMainDecisionsIndexRoute;
  '/$locale/org': typeof LocaleMainOrgIndexRoute;
  '/$locale/profile': typeof LocaleMainProfileIndexRoute;
  '/$locale/search': typeof LocaleMainSearchIndexRoute;
  '/$locale/admin/decisions/$instanceId': typeof LocaleMainAdminDecisionsInstanceIdRoute;
  '/$locale/decisions/$slug/edit': typeof LocaleNoHeaderDecisionsSlugEditRoute;
  '/$locale/org/$slug': typeof LocaleMainOrgSlugIndexRoute;
  '/$locale/profile/$slug': typeof LocaleMainProfileSlugIndexRoute;
  '/$locale/decisions/$slug/opengraph-image': typeof LocaleNoHeaderDecisionsSlugDecisionViewOpengraphImageRoute;
  '/$locale/decisions/$slug/assignments/$profileId': typeof LocaleNoHeaderDecisionsSlugAssignmentsProfileIdRoute;
  '/$locale/decisions/$slug/reviews/$reviewId': typeof LocaleNoHeaderDecisionsSlugReviewsReviewIdRoute;
  '/$locale/profile/$slug/posts/$postId': typeof LocaleNoHeaderProfileSlugPostsPostIdRoute;
  '/$locale/admin/decisions': typeof LocaleMainAdminDashboardDecisionsIndexRoute;
  '/$locale/admin/orgs': typeof LocaleMainAdminDashboardOrgsIndexRoute;
  '/$locale/admin/users': typeof LocaleMainAdminDashboardUsersIndexRoute;
  '/$locale/org/$slug/relationships': typeof LocaleMainOrgSlugRelationshipsIndexRoute;
  '/$locale/decisions/$slug/assignments': typeof LocaleNoHeaderDecisionsSlugAssignmentsIndexRoute;
  '/$locale/decisions/$slug/current/opengraph-image': typeof LocaleNoHeaderDecisionsSlugDecisionViewCurrentOpengraphImageRoute;
  '/$locale/decisions/$slug/proposal/$profileId/edit': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdEditRoute;
  '/$locale/decisions/$slug/proposal/$profileId/invite': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdInviteRoute;
  '/$locale/decisions/$slug/proposal/$profileId/reviews': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdReviewsRoute;
  '/$locale/profile/$slug/decisions/$id/current': typeof LocaleNoHeaderProfileSlugDecisionsIdCurrentRoute;
  '/$locale/decisions/$slug/current': typeof LocaleNoHeaderDecisionsSlugDecisionViewCurrentIndexRoute;
  '/$locale/decisions/$slug/proposal/$profileId': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdIndexRoute;
  '/$locale/profile/$slug/decisions/$id': typeof LocaleNoHeaderProfileSlugDecisionsIdIndexRoute;
  '/$locale/profile/$slug/decisions/$id/proposal/$profileId/edit': typeof LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdEditRoute;
  '/$locale/profile/$slug/decisions/$id/proposal/$profileId': typeof LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/$locale': typeof LocaleRouteRouteWithChildren;
  '/info': typeof InfoRouteRouteWithChildren;
  '/login': typeof LoginRouteRouteWithChildren;
  '/$locale/_main': typeof LocaleMainRouteRouteWithChildren;
  '/$locale/_noHeader': typeof LocaleNoHeaderRouteRouteWithChildren;
  '/$locale/start': typeof LocaleStartRouteRouteWithChildren;
  '/api/csp-report': typeof ApiCspReportRoute;
  '/api/waitlist-signup': typeof ApiWaitlistSignupRoute;
  '/info/columbus-addendum': typeof InfoColumbusAddendumRoute;
  '/info/community-commitments': typeof InfoCommunityCommitmentsRoute;
  '/info/privacy': typeof InfoPrivacyRoute;
  '/info/tos': typeof InfoTosRoute;
  '/login/': typeof LoginIndexRoute;
  '/$locale/_main/admin': typeof LocaleMainAdminRouteRouteWithChildren;
  '/$locale/_main/$': typeof LocaleMainSplatRoute;
  '/api/auth/callback': typeof ApiAuthCallbackRoute;
  '/api/auth/confirm': typeof ApiAuthConfirmRoute;
  '/api/embeds/embed.js': typeof ApiEmbedsEmbedDotjsRoute;
  '/api/otel/traces': typeof ApiOtelTracesRoute;
  '/$locale/_main/': typeof LocaleMainIndexRoute;
  '/$locale/start/': typeof LocaleStartIndexRoute;
  '/$locale/_main/admin/_dashboard': typeof LocaleMainAdminDashboardRouteRouteWithChildren;
  '/$locale/_noHeader/decisions/$slug': typeof LocaleNoHeaderDecisionsSlugRouteRouteWithChildren;
  '/api/embeds/api/iframe': typeof ApiEmbedsApiIframeRoute;
  '/$locale/_main/decisions/': typeof LocaleMainDecisionsIndexRoute;
  '/$locale/_main/org/': typeof LocaleMainOrgIndexRoute;
  '/$locale/_main/profile/': typeof LocaleMainProfileIndexRoute;
  '/$locale/_main/search/': typeof LocaleMainSearchIndexRoute;
  '/$locale/_noHeader/decisions/$slug/_decisionView': typeof LocaleNoHeaderDecisionsSlugDecisionViewRouteRouteWithChildren;
  '/$locale/_main/admin/decisions/$instanceId': typeof LocaleMainAdminDecisionsInstanceIdRoute;
  '/$locale/_noHeader/decisions/$slug/edit': typeof LocaleNoHeaderDecisionsSlugEditRoute;
  '/$locale/_main/admin/_dashboard/': typeof LocaleMainAdminDashboardIndexRoute;
  '/$locale/_main/org/$slug/': typeof LocaleMainOrgSlugIndexRoute;
  '/$locale/_main/profile/$slug/': typeof LocaleMainProfileSlugIndexRoute;
  '/$locale/_noHeader/decisions/$slug/_decisionView/opengraph-image': typeof LocaleNoHeaderDecisionsSlugDecisionViewOpengraphImageRoute;
  '/$locale/_noHeader/decisions/$slug/assignments/$profileId': typeof LocaleNoHeaderDecisionsSlugAssignmentsProfileIdRoute;
  '/$locale/_noHeader/decisions/$slug/reviews/$reviewId': typeof LocaleNoHeaderDecisionsSlugReviewsReviewIdRoute;
  '/$locale/_noHeader/profile/$slug/posts/$postId': typeof LocaleNoHeaderProfileSlugPostsPostIdRoute;
  '/$locale/_main/admin/_dashboard/decisions/': typeof LocaleMainAdminDashboardDecisionsIndexRoute;
  '/$locale/_main/admin/_dashboard/orgs/': typeof LocaleMainAdminDashboardOrgsIndexRoute;
  '/$locale/_main/admin/_dashboard/users/': typeof LocaleMainAdminDashboardUsersIndexRoute;
  '/$locale/_main/org/$slug/relationships/': typeof LocaleMainOrgSlugRelationshipsIndexRoute;
  '/$locale/_noHeader/decisions/$slug/_decisionView/': typeof LocaleNoHeaderDecisionsSlugDecisionViewIndexRoute;
  '/$locale/_noHeader/decisions/$slug/assignments/': typeof LocaleNoHeaderDecisionsSlugAssignmentsIndexRoute;
  '/$locale/_noHeader/decisions/$slug/_decisionView/current/opengraph-image': typeof LocaleNoHeaderDecisionsSlugDecisionViewCurrentOpengraphImageRoute;
  '/$locale/_noHeader/decisions/$slug/proposal/$profileId/edit': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdEditRoute;
  '/$locale/_noHeader/decisions/$slug/proposal/$profileId/invite': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdInviteRoute;
  '/$locale/_noHeader/decisions/$slug/proposal/$profileId/reviews': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdReviewsRoute;
  '/$locale/_noHeader/profile/$slug/decisions/$id/current': typeof LocaleNoHeaderProfileSlugDecisionsIdCurrentRoute;
  '/$locale/_noHeader/decisions/$slug/_decisionView/current/': typeof LocaleNoHeaderDecisionsSlugDecisionViewCurrentIndexRoute;
  '/$locale/_noHeader/decisions/$slug/proposal/$profileId/': typeof LocaleNoHeaderDecisionsSlugProposalProfileIdIndexRoute;
  '/$locale/_noHeader/profile/$slug/decisions/$id/': typeof LocaleNoHeaderProfileSlugDecisionsIdIndexRoute;
  '/$locale/_noHeader/profile/$slug/decisions/$id/proposal/$profileId/edit': typeof LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdEditRoute;
  '/$locale/_noHeader/profile/$slug/decisions/$id/proposal/$profileId/': typeof LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/$locale'
    | '/info'
    | '/login'
    | '/$locale/start'
    | '/api/csp-report'
    | '/api/waitlist-signup'
    | '/info/columbus-addendum'
    | '/info/community-commitments'
    | '/info/privacy'
    | '/info/tos'
    | '/login/'
    | '/$locale/admin'
    | '/$locale/$'
    | '/api/auth/callback'
    | '/api/auth/confirm'
    | '/api/embeds/embed.js'
    | '/api/otel/traces'
    | '/$locale/'
    | '/$locale/start/'
    | '/$locale/decisions/$slug'
    | '/api/embeds/api/iframe'
    | '/$locale/decisions/'
    | '/$locale/org/'
    | '/$locale/profile/'
    | '/$locale/search/'
    | '/$locale/admin/decisions/$instanceId'
    | '/$locale/decisions/$slug/edit'
    | '/$locale/admin/'
    | '/$locale/org/$slug/'
    | '/$locale/profile/$slug/'
    | '/$locale/decisions/$slug/opengraph-image'
    | '/$locale/decisions/$slug/assignments/$profileId'
    | '/$locale/decisions/$slug/reviews/$reviewId'
    | '/$locale/profile/$slug/posts/$postId'
    | '/$locale/admin/decisions/'
    | '/$locale/admin/orgs/'
    | '/$locale/admin/users/'
    | '/$locale/org/$slug/relationships/'
    | '/$locale/decisions/$slug/'
    | '/$locale/decisions/$slug/assignments/'
    | '/$locale/decisions/$slug/current/opengraph-image'
    | '/$locale/decisions/$slug/proposal/$profileId/edit'
    | '/$locale/decisions/$slug/proposal/$profileId/invite'
    | '/$locale/decisions/$slug/proposal/$profileId/reviews'
    | '/$locale/profile/$slug/decisions/$id/current'
    | '/$locale/decisions/$slug/current/'
    | '/$locale/decisions/$slug/proposal/$profileId/'
    | '/$locale/profile/$slug/decisions/$id/'
    | '/$locale/profile/$slug/decisions/$id/proposal/$profileId/edit'
    | '/$locale/profile/$slug/decisions/$id/proposal/$profileId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/$locale'
    | '/info'
    | '/api/csp-report'
    | '/api/waitlist-signup'
    | '/info/columbus-addendum'
    | '/info/community-commitments'
    | '/info/privacy'
    | '/info/tos'
    | '/login'
    | '/$locale/admin'
    | '/$locale/$'
    | '/api/auth/callback'
    | '/api/auth/confirm'
    | '/api/embeds/embed.js'
    | '/api/otel/traces'
    | '/$locale/start'
    | '/$locale/decisions/$slug'
    | '/api/embeds/api/iframe'
    | '/$locale/decisions'
    | '/$locale/org'
    | '/$locale/profile'
    | '/$locale/search'
    | '/$locale/admin/decisions/$instanceId'
    | '/$locale/decisions/$slug/edit'
    | '/$locale/org/$slug'
    | '/$locale/profile/$slug'
    | '/$locale/decisions/$slug/opengraph-image'
    | '/$locale/decisions/$slug/assignments/$profileId'
    | '/$locale/decisions/$slug/reviews/$reviewId'
    | '/$locale/profile/$slug/posts/$postId'
    | '/$locale/admin/decisions'
    | '/$locale/admin/orgs'
    | '/$locale/admin/users'
    | '/$locale/org/$slug/relationships'
    | '/$locale/decisions/$slug/assignments'
    | '/$locale/decisions/$slug/current/opengraph-image'
    | '/$locale/decisions/$slug/proposal/$profileId/edit'
    | '/$locale/decisions/$slug/proposal/$profileId/invite'
    | '/$locale/decisions/$slug/proposal/$profileId/reviews'
    | '/$locale/profile/$slug/decisions/$id/current'
    | '/$locale/decisions/$slug/current'
    | '/$locale/decisions/$slug/proposal/$profileId'
    | '/$locale/profile/$slug/decisions/$id'
    | '/$locale/profile/$slug/decisions/$id/proposal/$profileId/edit'
    | '/$locale/profile/$slug/decisions/$id/proposal/$profileId';
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/info'
    | '/login'
    | '/$locale/_main'
    | '/$locale/_noHeader'
    | '/$locale/start'
    | '/api/csp-report'
    | '/api/waitlist-signup'
    | '/info/columbus-addendum'
    | '/info/community-commitments'
    | '/info/privacy'
    | '/info/tos'
    | '/login/'
    | '/$locale/_main/admin'
    | '/$locale/_main/$'
    | '/api/auth/callback'
    | '/api/auth/confirm'
    | '/api/embeds/embed.js'
    | '/api/otel/traces'
    | '/$locale/_main/'
    | '/$locale/start/'
    | '/$locale/_main/admin/_dashboard'
    | '/$locale/_noHeader/decisions/$slug'
    | '/api/embeds/api/iframe'
    | '/$locale/_main/decisions/'
    | '/$locale/_main/org/'
    | '/$locale/_main/profile/'
    | '/$locale/_main/search/'
    | '/$locale/_noHeader/decisions/$slug/_decisionView'
    | '/$locale/_main/admin/decisions/$instanceId'
    | '/$locale/_noHeader/decisions/$slug/edit'
    | '/$locale/_main/admin/_dashboard/'
    | '/$locale/_main/org/$slug/'
    | '/$locale/_main/profile/$slug/'
    | '/$locale/_noHeader/decisions/$slug/_decisionView/opengraph-image'
    | '/$locale/_noHeader/decisions/$slug/assignments/$profileId'
    | '/$locale/_noHeader/decisions/$slug/reviews/$reviewId'
    | '/$locale/_noHeader/profile/$slug/posts/$postId'
    | '/$locale/_main/admin/_dashboard/decisions/'
    | '/$locale/_main/admin/_dashboard/orgs/'
    | '/$locale/_main/admin/_dashboard/users/'
    | '/$locale/_main/org/$slug/relationships/'
    | '/$locale/_noHeader/decisions/$slug/_decisionView/'
    | '/$locale/_noHeader/decisions/$slug/assignments/'
    | '/$locale/_noHeader/decisions/$slug/_decisionView/current/opengraph-image'
    | '/$locale/_noHeader/decisions/$slug/proposal/$profileId/edit'
    | '/$locale/_noHeader/decisions/$slug/proposal/$profileId/invite'
    | '/$locale/_noHeader/decisions/$slug/proposal/$profileId/reviews'
    | '/$locale/_noHeader/profile/$slug/decisions/$id/current'
    | '/$locale/_noHeader/decisions/$slug/_decisionView/current/'
    | '/$locale/_noHeader/decisions/$slug/proposal/$profileId/'
    | '/$locale/_noHeader/profile/$slug/decisions/$id/'
    | '/$locale/_noHeader/profile/$slug/decisions/$id/proposal/$profileId/edit'
    | '/$locale/_noHeader/profile/$slug/decisions/$id/proposal/$profileId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren;
  InfoRouteRoute: typeof InfoRouteRouteWithChildren;
  LoginRouteRoute: typeof LoginRouteRouteWithChildren;
  ApiCspReportRoute: typeof ApiCspReportRoute;
  ApiWaitlistSignupRoute: typeof ApiWaitlistSignupRoute;
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute;
  ApiAuthConfirmRoute: typeof ApiAuthConfirmRoute;
  ApiEmbedsEmbedDotjsRoute: typeof ApiEmbedsEmbedDotjsRoute;
  ApiOtelTracesRoute: typeof ApiOtelTracesRoute;
  ApiEmbedsApiIframeRoute: typeof ApiEmbedsApiIframeRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$locale': {
      id: '/$locale';
      path: '/$locale';
      fullPath: '/$locale';
      preLoaderRoute: typeof LocaleRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/info': {
      id: '/info';
      path: '/info';
      fullPath: '/info';
      preLoaderRoute: typeof InfoRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$locale/_main': {
      id: '/$locale/_main';
      path: '';
      fullPath: '/$locale';
      preLoaderRoute: typeof LocaleMainRouteRouteImport;
      parentRoute: typeof LocaleRouteRoute;
    };
    '/$locale/_noHeader': {
      id: '/$locale/_noHeader';
      path: '';
      fullPath: '/$locale';
      preLoaderRoute: typeof LocaleNoHeaderRouteRouteImport;
      parentRoute: typeof LocaleRouteRoute;
    };
    '/$locale/start': {
      id: '/$locale/start';
      path: '/start';
      fullPath: '/$locale/start';
      preLoaderRoute: typeof LocaleStartRouteRouteImport;
      parentRoute: typeof LocaleRouteRoute;
    };
    '/api/csp-report': {
      id: '/api/csp-report';
      path: '/api/csp-report';
      fullPath: '/api/csp-report';
      preLoaderRoute: typeof ApiCspReportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/waitlist-signup': {
      id: '/api/waitlist-signup';
      path: '/api/waitlist-signup';
      fullPath: '/api/waitlist-signup';
      preLoaderRoute: typeof ApiWaitlistSignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/info/columbus-addendum': {
      id: '/info/columbus-addendum';
      path: '/columbus-addendum';
      fullPath: '/info/columbus-addendum';
      preLoaderRoute: typeof InfoColumbusAddendumRouteImport;
      parentRoute: typeof InfoRouteRoute;
    };
    '/info/community-commitments': {
      id: '/info/community-commitments';
      path: '/community-commitments';
      fullPath: '/info/community-commitments';
      preLoaderRoute: typeof InfoCommunityCommitmentsRouteImport;
      parentRoute: typeof InfoRouteRoute;
    };
    '/info/privacy': {
      id: '/info/privacy';
      path: '/privacy';
      fullPath: '/info/privacy';
      preLoaderRoute: typeof InfoPrivacyRouteImport;
      parentRoute: typeof InfoRouteRoute;
    };
    '/info/tos': {
      id: '/info/tos';
      path: '/tos';
      fullPath: '/info/tos';
      preLoaderRoute: typeof InfoTosRouteImport;
      parentRoute: typeof InfoRouteRoute;
    };
    '/login/': {
      id: '/login/';
      path: '/';
      fullPath: '/login/';
      preLoaderRoute: typeof LoginIndexRouteImport;
      parentRoute: typeof LoginRouteRoute;
    };
    '/$locale/_main/': {
      id: '/$locale/_main/';
      path: '/';
      fullPath: '/$locale/';
      preLoaderRoute: typeof LocaleMainIndexRouteImport;
      parentRoute: typeof LocaleMainRouteRoute;
    };
    '/$locale/_main/$': {
      id: '/$locale/_main/$';
      path: '/$';
      fullPath: '/$locale/$';
      preLoaderRoute: typeof LocaleMainSplatRouteImport;
      parentRoute: typeof LocaleMainRouteRoute;
    };
    '/$locale/_main/admin': {
      id: '/$locale/_main/admin';
      path: '/admin';
      fullPath: '/$locale/admin';
      preLoaderRoute: typeof LocaleMainAdminRouteRouteImport;
      parentRoute: typeof LocaleMainRouteRoute;
    };
    '/$locale/start/': {
      id: '/$locale/start/';
      path: '/';
      fullPath: '/$locale/start/';
      preLoaderRoute: typeof LocaleStartIndexRouteImport;
      parentRoute: typeof LocaleStartRouteRoute;
    };
    '/api/auth/callback': {
      id: '/api/auth/callback';
      path: '/api/auth/callback';
      fullPath: '/api/auth/callback';
      preLoaderRoute: typeof ApiAuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/confirm': {
      id: '/api/auth/confirm';
      path: '/api/auth/confirm';
      fullPath: '/api/auth/confirm';
      preLoaderRoute: typeof ApiAuthConfirmRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/embeds/embed.js': {
      id: '/api/embeds/embed.js';
      path: '/api/embeds/embed.js';
      fullPath: '/api/embeds/embed.js';
      preLoaderRoute: typeof ApiEmbedsEmbedDotjsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/otel/traces': {
      id: '/api/otel/traces';
      path: '/api/otel/traces';
      fullPath: '/api/otel/traces';
      preLoaderRoute: typeof ApiOtelTracesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$locale/_main/admin/_dashboard': {
      id: '/$locale/_main/admin/_dashboard';
      path: '';
      fullPath: '/$locale/admin';
      preLoaderRoute: typeof LocaleMainAdminDashboardRouteRouteImport;
      parentRoute: typeof LocaleMainAdminRouteRoute;
    };
    '/$locale/_main/decisions/': {
      id: '/$locale/_main/decisions/';
      path: '/decisions';
      fullPath: '/$locale/decisions/';
      preLoaderRoute: typeof LocaleMainDecisionsIndexRouteImport;
      parentRoute: typeof LocaleMainRouteRoute;
    };
    '/$locale/_main/org/': {
      id: '/$locale/_main/org/';
      path: '/org';
      fullPath: '/$locale/org/';
      preLoaderRoute: typeof LocaleMainOrgIndexRouteImport;
      parentRoute: typeof LocaleMainRouteRoute;
    };
    '/$locale/_main/profile/': {
      id: '/$locale/_main/profile/';
      path: '/profile';
      fullPath: '/$locale/profile/';
      preLoaderRoute: typeof LocaleMainProfileIndexRouteImport;
      parentRoute: typeof LocaleMainRouteRoute;
    };
    '/$locale/_main/search/': {
      id: '/$locale/_main/search/';
      path: '/search';
      fullPath: '/$locale/search/';
      preLoaderRoute: typeof LocaleMainSearchIndexRouteImport;
      parentRoute: typeof LocaleMainRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug': {
      id: '/$locale/_noHeader/decisions/$slug';
      path: '/decisions/$slug';
      fullPath: '/$locale/decisions/$slug';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugRouteRouteImport;
      parentRoute: typeof LocaleNoHeaderRouteRoute;
    };
    '/api/embeds/api/iframe': {
      id: '/api/embeds/api/iframe';
      path: '/api/embeds/api/iframe';
      fullPath: '/api/embeds/api/iframe';
      preLoaderRoute: typeof ApiEmbedsApiIframeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$locale/_main/admin/_dashboard/': {
      id: '/$locale/_main/admin/_dashboard/';
      path: '/';
      fullPath: '/$locale/admin/';
      preLoaderRoute: typeof LocaleMainAdminDashboardIndexRouteImport;
      parentRoute: typeof LocaleMainAdminDashboardRouteRoute;
    };
    '/$locale/_main/admin/decisions/$instanceId': {
      id: '/$locale/_main/admin/decisions/$instanceId';
      path: '/decisions/$instanceId';
      fullPath: '/$locale/admin/decisions/$instanceId';
      preLoaderRoute: typeof LocaleMainAdminDecisionsInstanceIdRouteImport;
      parentRoute: typeof LocaleMainAdminRouteRoute;
    };
    '/$locale/_main/org/$slug/': {
      id: '/$locale/_main/org/$slug/';
      path: '/org/$slug';
      fullPath: '/$locale/org/$slug/';
      preLoaderRoute: typeof LocaleMainOrgSlugIndexRouteImport;
      parentRoute: typeof LocaleMainRouteRoute;
    };
    '/$locale/_main/profile/$slug/': {
      id: '/$locale/_main/profile/$slug/';
      path: '/profile/$slug';
      fullPath: '/$locale/profile/$slug/';
      preLoaderRoute: typeof LocaleMainProfileSlugIndexRouteImport;
      parentRoute: typeof LocaleMainRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/_decisionView': {
      id: '/$locale/_noHeader/decisions/$slug/_decisionView';
      path: '';
      fullPath: '/$locale/decisions/$slug';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewRouteRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/edit': {
      id: '/$locale/_noHeader/decisions/$slug/edit';
      path: '/edit';
      fullPath: '/$locale/decisions/$slug/edit';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugEditRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugRouteRoute;
    };
    '/$locale/_main/admin/_dashboard/decisions/': {
      id: '/$locale/_main/admin/_dashboard/decisions/';
      path: '/decisions';
      fullPath: '/$locale/admin/decisions/';
      preLoaderRoute: typeof LocaleMainAdminDashboardDecisionsIndexRouteImport;
      parentRoute: typeof LocaleMainAdminDashboardRouteRoute;
    };
    '/$locale/_main/admin/_dashboard/orgs/': {
      id: '/$locale/_main/admin/_dashboard/orgs/';
      path: '/orgs';
      fullPath: '/$locale/admin/orgs/';
      preLoaderRoute: typeof LocaleMainAdminDashboardOrgsIndexRouteImport;
      parentRoute: typeof LocaleMainAdminDashboardRouteRoute;
    };
    '/$locale/_main/admin/_dashboard/users/': {
      id: '/$locale/_main/admin/_dashboard/users/';
      path: '/users';
      fullPath: '/$locale/admin/users/';
      preLoaderRoute: typeof LocaleMainAdminDashboardUsersIndexRouteImport;
      parentRoute: typeof LocaleMainAdminDashboardRouteRoute;
    };
    '/$locale/_main/org/$slug/relationships/': {
      id: '/$locale/_main/org/$slug/relationships/';
      path: '/org/$slug/relationships';
      fullPath: '/$locale/org/$slug/relationships/';
      preLoaderRoute: typeof LocaleMainOrgSlugRelationshipsIndexRouteImport;
      parentRoute: typeof LocaleMainRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/_decisionView/': {
      id: '/$locale/_noHeader/decisions/$slug/_decisionView/';
      path: '/';
      fullPath: '/$locale/decisions/$slug/';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewIndexRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/_decisionView/opengraph-image': {
      id: '/$locale/_noHeader/decisions/$slug/_decisionView/opengraph-image';
      path: '/opengraph-image';
      fullPath: '/$locale/decisions/$slug/opengraph-image';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewOpengraphImageRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/assignments/': {
      id: '/$locale/_noHeader/decisions/$slug/assignments/';
      path: '/assignments';
      fullPath: '/$locale/decisions/$slug/assignments/';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugAssignmentsIndexRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/assignments/$profileId': {
      id: '/$locale/_noHeader/decisions/$slug/assignments/$profileId';
      path: '/assignments/$profileId';
      fullPath: '/$locale/decisions/$slug/assignments/$profileId';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugAssignmentsProfileIdRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/reviews/$reviewId': {
      id: '/$locale/_noHeader/decisions/$slug/reviews/$reviewId';
      path: '/reviews/$reviewId';
      fullPath: '/$locale/decisions/$slug/reviews/$reviewId';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugReviewsReviewIdRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugRouteRoute;
    };
    '/$locale/_noHeader/profile/$slug/posts/$postId': {
      id: '/$locale/_noHeader/profile/$slug/posts/$postId';
      path: '/profile/$slug/posts/$postId';
      fullPath: '/$locale/profile/$slug/posts/$postId';
      preLoaderRoute: typeof LocaleNoHeaderProfileSlugPostsPostIdRouteImport;
      parentRoute: typeof LocaleNoHeaderRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/_decisionView/current/': {
      id: '/$locale/_noHeader/decisions/$slug/_decisionView/current/';
      path: '/current';
      fullPath: '/$locale/decisions/$slug/current/';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewCurrentIndexRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/_decisionView/current/opengraph-image': {
      id: '/$locale/_noHeader/decisions/$slug/_decisionView/current/opengraph-image';
      path: '/current/opengraph-image';
      fullPath: '/$locale/decisions/$slug/current/opengraph-image';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewCurrentOpengraphImageRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/proposal/$profileId/': {
      id: '/$locale/_noHeader/decisions/$slug/proposal/$profileId/';
      path: '/proposal/$profileId';
      fullPath: '/$locale/decisions/$slug/proposal/$profileId/';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugProposalProfileIdIndexRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/proposal/$profileId/edit': {
      id: '/$locale/_noHeader/decisions/$slug/proposal/$profileId/edit';
      path: '/proposal/$profileId/edit';
      fullPath: '/$locale/decisions/$slug/proposal/$profileId/edit';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugProposalProfileIdEditRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/proposal/$profileId/invite': {
      id: '/$locale/_noHeader/decisions/$slug/proposal/$profileId/invite';
      path: '/proposal/$profileId/invite';
      fullPath: '/$locale/decisions/$slug/proposal/$profileId/invite';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugProposalProfileIdInviteRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugRouteRoute;
    };
    '/$locale/_noHeader/decisions/$slug/proposal/$profileId/reviews': {
      id: '/$locale/_noHeader/decisions/$slug/proposal/$profileId/reviews';
      path: '/proposal/$profileId/reviews';
      fullPath: '/$locale/decisions/$slug/proposal/$profileId/reviews';
      preLoaderRoute: typeof LocaleNoHeaderDecisionsSlugProposalProfileIdReviewsRouteImport;
      parentRoute: typeof LocaleNoHeaderDecisionsSlugRouteRoute;
    };
    '/$locale/_noHeader/profile/$slug/decisions/$id/': {
      id: '/$locale/_noHeader/profile/$slug/decisions/$id/';
      path: '/profile/$slug/decisions/$id';
      fullPath: '/$locale/profile/$slug/decisions/$id/';
      preLoaderRoute: typeof LocaleNoHeaderProfileSlugDecisionsIdIndexRouteImport;
      parentRoute: typeof LocaleNoHeaderRouteRoute;
    };
    '/$locale/_noHeader/profile/$slug/decisions/$id/current': {
      id: '/$locale/_noHeader/profile/$slug/decisions/$id/current';
      path: '/profile/$slug/decisions/$id/current';
      fullPath: '/$locale/profile/$slug/decisions/$id/current';
      preLoaderRoute: typeof LocaleNoHeaderProfileSlugDecisionsIdCurrentRouteImport;
      parentRoute: typeof LocaleNoHeaderRouteRoute;
    };
    '/$locale/_noHeader/profile/$slug/decisions/$id/proposal/$profileId/': {
      id: '/$locale/_noHeader/profile/$slug/decisions/$id/proposal/$profileId/';
      path: '/profile/$slug/decisions/$id/proposal/$profileId';
      fullPath: '/$locale/profile/$slug/decisions/$id/proposal/$profileId/';
      preLoaderRoute: typeof LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdIndexRouteImport;
      parentRoute: typeof LocaleNoHeaderRouteRoute;
    };
    '/$locale/_noHeader/profile/$slug/decisions/$id/proposal/$profileId/edit': {
      id: '/$locale/_noHeader/profile/$slug/decisions/$id/proposal/$profileId/edit';
      path: '/profile/$slug/decisions/$id/proposal/$profileId/edit';
      fullPath: '/$locale/profile/$slug/decisions/$id/proposal/$profileId/edit';
      preLoaderRoute: typeof LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdEditRouteImport;
      parentRoute: typeof LocaleNoHeaderRouteRoute;
    };
  }
}

interface LocaleMainAdminDashboardRouteRouteChildren {
  LocaleMainAdminDashboardIndexRoute: typeof LocaleMainAdminDashboardIndexRoute;
  LocaleMainAdminDashboardDecisionsIndexRoute: typeof LocaleMainAdminDashboardDecisionsIndexRoute;
  LocaleMainAdminDashboardOrgsIndexRoute: typeof LocaleMainAdminDashboardOrgsIndexRoute;
  LocaleMainAdminDashboardUsersIndexRoute: typeof LocaleMainAdminDashboardUsersIndexRoute;
}

const LocaleMainAdminDashboardRouteRouteChildren: LocaleMainAdminDashboardRouteRouteChildren =
  {
    LocaleMainAdminDashboardIndexRoute: LocaleMainAdminDashboardIndexRoute,
    LocaleMainAdminDashboardDecisionsIndexRoute:
      LocaleMainAdminDashboardDecisionsIndexRoute,
    LocaleMainAdminDashboardOrgsIndexRoute:
      LocaleMainAdminDashboardOrgsIndexRoute,
    LocaleMainAdminDashboardUsersIndexRoute:
      LocaleMainAdminDashboardUsersIndexRoute,
  };

const LocaleMainAdminDashboardRouteRouteWithChildren =
  LocaleMainAdminDashboardRouteRoute._addFileChildren(
    LocaleMainAdminDashboardRouteRouteChildren,
  );

interface LocaleMainAdminRouteRouteChildren {
  LocaleMainAdminDashboardRouteRoute: typeof LocaleMainAdminDashboardRouteRouteWithChildren;
  LocaleMainAdminDecisionsInstanceIdRoute: typeof LocaleMainAdminDecisionsInstanceIdRoute;
}

const LocaleMainAdminRouteRouteChildren: LocaleMainAdminRouteRouteChildren = {
  LocaleMainAdminDashboardRouteRoute:
    LocaleMainAdminDashboardRouteRouteWithChildren,
  LocaleMainAdminDecisionsInstanceIdRoute:
    LocaleMainAdminDecisionsInstanceIdRoute,
};

const LocaleMainAdminRouteRouteWithChildren =
  LocaleMainAdminRouteRoute._addFileChildren(LocaleMainAdminRouteRouteChildren);

interface LocaleMainRouteRouteChildren {
  LocaleMainAdminRouteRoute: typeof LocaleMainAdminRouteRouteWithChildren;
  LocaleMainSplatRoute: typeof LocaleMainSplatRoute;
  LocaleMainIndexRoute: typeof LocaleMainIndexRoute;
  LocaleMainDecisionsIndexRoute: typeof LocaleMainDecisionsIndexRoute;
  LocaleMainOrgIndexRoute: typeof LocaleMainOrgIndexRoute;
  LocaleMainProfileIndexRoute: typeof LocaleMainProfileIndexRoute;
  LocaleMainSearchIndexRoute: typeof LocaleMainSearchIndexRoute;
  LocaleMainOrgSlugIndexRoute: typeof LocaleMainOrgSlugIndexRoute;
  LocaleMainProfileSlugIndexRoute: typeof LocaleMainProfileSlugIndexRoute;
  LocaleMainOrgSlugRelationshipsIndexRoute: typeof LocaleMainOrgSlugRelationshipsIndexRoute;
}

const LocaleMainRouteRouteChildren: LocaleMainRouteRouteChildren = {
  LocaleMainAdminRouteRoute: LocaleMainAdminRouteRouteWithChildren,
  LocaleMainSplatRoute: LocaleMainSplatRoute,
  LocaleMainIndexRoute: LocaleMainIndexRoute,
  LocaleMainDecisionsIndexRoute: LocaleMainDecisionsIndexRoute,
  LocaleMainOrgIndexRoute: LocaleMainOrgIndexRoute,
  LocaleMainProfileIndexRoute: LocaleMainProfileIndexRoute,
  LocaleMainSearchIndexRoute: LocaleMainSearchIndexRoute,
  LocaleMainOrgSlugIndexRoute: LocaleMainOrgSlugIndexRoute,
  LocaleMainProfileSlugIndexRoute: LocaleMainProfileSlugIndexRoute,
  LocaleMainOrgSlugRelationshipsIndexRoute:
    LocaleMainOrgSlugRelationshipsIndexRoute,
};

const LocaleMainRouteRouteWithChildren = LocaleMainRouteRoute._addFileChildren(
  LocaleMainRouteRouteChildren,
);

interface LocaleNoHeaderDecisionsSlugDecisionViewRouteRouteChildren {
  LocaleNoHeaderDecisionsSlugDecisionViewOpengraphImageRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewOpengraphImageRoute;
  LocaleNoHeaderDecisionsSlugDecisionViewIndexRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewIndexRoute;
  LocaleNoHeaderDecisionsSlugDecisionViewCurrentOpengraphImageRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewCurrentOpengraphImageRoute;
  LocaleNoHeaderDecisionsSlugDecisionViewCurrentIndexRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewCurrentIndexRoute;
}

const LocaleNoHeaderDecisionsSlugDecisionViewRouteRouteChildren: LocaleNoHeaderDecisionsSlugDecisionViewRouteRouteChildren =
  {
    LocaleNoHeaderDecisionsSlugDecisionViewOpengraphImageRoute:
      LocaleNoHeaderDecisionsSlugDecisionViewOpengraphImageRoute,
    LocaleNoHeaderDecisionsSlugDecisionViewIndexRoute:
      LocaleNoHeaderDecisionsSlugDecisionViewIndexRoute,
    LocaleNoHeaderDecisionsSlugDecisionViewCurrentOpengraphImageRoute:
      LocaleNoHeaderDecisionsSlugDecisionViewCurrentOpengraphImageRoute,
    LocaleNoHeaderDecisionsSlugDecisionViewCurrentIndexRoute:
      LocaleNoHeaderDecisionsSlugDecisionViewCurrentIndexRoute,
  };

const LocaleNoHeaderDecisionsSlugDecisionViewRouteRouteWithChildren =
  LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute._addFileChildren(
    LocaleNoHeaderDecisionsSlugDecisionViewRouteRouteChildren,
  );

interface LocaleNoHeaderDecisionsSlugRouteRouteChildren {
  LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute: typeof LocaleNoHeaderDecisionsSlugDecisionViewRouteRouteWithChildren;
  LocaleNoHeaderDecisionsSlugEditRoute: typeof LocaleNoHeaderDecisionsSlugEditRoute;
  LocaleNoHeaderDecisionsSlugAssignmentsProfileIdRoute: typeof LocaleNoHeaderDecisionsSlugAssignmentsProfileIdRoute;
  LocaleNoHeaderDecisionsSlugReviewsReviewIdRoute: typeof LocaleNoHeaderDecisionsSlugReviewsReviewIdRoute;
  LocaleNoHeaderDecisionsSlugAssignmentsIndexRoute: typeof LocaleNoHeaderDecisionsSlugAssignmentsIndexRoute;
  LocaleNoHeaderDecisionsSlugProposalProfileIdEditRoute: typeof LocaleNoHeaderDecisionsSlugProposalProfileIdEditRoute;
  LocaleNoHeaderDecisionsSlugProposalProfileIdInviteRoute: typeof LocaleNoHeaderDecisionsSlugProposalProfileIdInviteRoute;
  LocaleNoHeaderDecisionsSlugProposalProfileIdReviewsRoute: typeof LocaleNoHeaderDecisionsSlugProposalProfileIdReviewsRoute;
  LocaleNoHeaderDecisionsSlugProposalProfileIdIndexRoute: typeof LocaleNoHeaderDecisionsSlugProposalProfileIdIndexRoute;
}

const LocaleNoHeaderDecisionsSlugRouteRouteChildren: LocaleNoHeaderDecisionsSlugRouteRouteChildren =
  {
    LocaleNoHeaderDecisionsSlugDecisionViewRouteRoute:
      LocaleNoHeaderDecisionsSlugDecisionViewRouteRouteWithChildren,
    LocaleNoHeaderDecisionsSlugEditRoute: LocaleNoHeaderDecisionsSlugEditRoute,
    LocaleNoHeaderDecisionsSlugAssignmentsProfileIdRoute:
      LocaleNoHeaderDecisionsSlugAssignmentsProfileIdRoute,
    LocaleNoHeaderDecisionsSlugReviewsReviewIdRoute:
      LocaleNoHeaderDecisionsSlugReviewsReviewIdRoute,
    LocaleNoHeaderDecisionsSlugAssignmentsIndexRoute:
      LocaleNoHeaderDecisionsSlugAssignmentsIndexRoute,
    LocaleNoHeaderDecisionsSlugProposalProfileIdEditRoute:
      LocaleNoHeaderDecisionsSlugProposalProfileIdEditRoute,
    LocaleNoHeaderDecisionsSlugProposalProfileIdInviteRoute:
      LocaleNoHeaderDecisionsSlugProposalProfileIdInviteRoute,
    LocaleNoHeaderDecisionsSlugProposalProfileIdReviewsRoute:
      LocaleNoHeaderDecisionsSlugProposalProfileIdReviewsRoute,
    LocaleNoHeaderDecisionsSlugProposalProfileIdIndexRoute:
      LocaleNoHeaderDecisionsSlugProposalProfileIdIndexRoute,
  };

const LocaleNoHeaderDecisionsSlugRouteRouteWithChildren =
  LocaleNoHeaderDecisionsSlugRouteRoute._addFileChildren(
    LocaleNoHeaderDecisionsSlugRouteRouteChildren,
  );

interface LocaleNoHeaderRouteRouteChildren {
  LocaleNoHeaderDecisionsSlugRouteRoute: typeof LocaleNoHeaderDecisionsSlugRouteRouteWithChildren;
  LocaleNoHeaderProfileSlugPostsPostIdRoute: typeof LocaleNoHeaderProfileSlugPostsPostIdRoute;
  LocaleNoHeaderProfileSlugDecisionsIdCurrentRoute: typeof LocaleNoHeaderProfileSlugDecisionsIdCurrentRoute;
  LocaleNoHeaderProfileSlugDecisionsIdIndexRoute: typeof LocaleNoHeaderProfileSlugDecisionsIdIndexRoute;
  LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdEditRoute: typeof LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdEditRoute;
  LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdIndexRoute: typeof LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdIndexRoute;
}

const LocaleNoHeaderRouteRouteChildren: LocaleNoHeaderRouteRouteChildren = {
  LocaleNoHeaderDecisionsSlugRouteRoute:
    LocaleNoHeaderDecisionsSlugRouteRouteWithChildren,
  LocaleNoHeaderProfileSlugPostsPostIdRoute:
    LocaleNoHeaderProfileSlugPostsPostIdRoute,
  LocaleNoHeaderProfileSlugDecisionsIdCurrentRoute:
    LocaleNoHeaderProfileSlugDecisionsIdCurrentRoute,
  LocaleNoHeaderProfileSlugDecisionsIdIndexRoute:
    LocaleNoHeaderProfileSlugDecisionsIdIndexRoute,
  LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdEditRoute:
    LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdEditRoute,
  LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdIndexRoute:
    LocaleNoHeaderProfileSlugDecisionsIdProposalProfileIdIndexRoute,
};

const LocaleNoHeaderRouteRouteWithChildren =
  LocaleNoHeaderRouteRoute._addFileChildren(LocaleNoHeaderRouteRouteChildren);

interface LocaleStartRouteRouteChildren {
  LocaleStartIndexRoute: typeof LocaleStartIndexRoute;
}

const LocaleStartRouteRouteChildren: LocaleStartRouteRouteChildren = {
  LocaleStartIndexRoute: LocaleStartIndexRoute,
};

const LocaleStartRouteRouteWithChildren =
  LocaleStartRouteRoute._addFileChildren(LocaleStartRouteRouteChildren);

interface LocaleRouteRouteChildren {
  LocaleMainRouteRoute: typeof LocaleMainRouteRouteWithChildren;
  LocaleNoHeaderRouteRoute: typeof LocaleNoHeaderRouteRouteWithChildren;
  LocaleStartRouteRoute: typeof LocaleStartRouteRouteWithChildren;
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleMainRouteRoute: LocaleMainRouteRouteWithChildren,
  LocaleNoHeaderRouteRoute: LocaleNoHeaderRouteRouteWithChildren,
  LocaleStartRouteRoute: LocaleStartRouteRouteWithChildren,
};

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
);

interface InfoRouteRouteChildren {
  InfoColumbusAddendumRoute: typeof InfoColumbusAddendumRoute;
  InfoCommunityCommitmentsRoute: typeof InfoCommunityCommitmentsRoute;
  InfoPrivacyRoute: typeof InfoPrivacyRoute;
  InfoTosRoute: typeof InfoTosRoute;
}

const InfoRouteRouteChildren: InfoRouteRouteChildren = {
  InfoColumbusAddendumRoute: InfoColumbusAddendumRoute,
  InfoCommunityCommitmentsRoute: InfoCommunityCommitmentsRoute,
  InfoPrivacyRoute: InfoPrivacyRoute,
  InfoTosRoute: InfoTosRoute,
};

const InfoRouteRouteWithChildren = InfoRouteRoute._addFileChildren(
  InfoRouteRouteChildren,
);

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute;
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
};

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  InfoRouteRoute: InfoRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  ApiCspReportRoute: ApiCspReportRoute,
  ApiWaitlistSignupRoute: ApiWaitlistSignupRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthConfirmRoute: ApiAuthConfirmRoute,
  ApiEmbedsEmbedDotjsRoute: ApiEmbedsEmbedDotjsRoute,
  ApiOtelTracesRoute: ApiOtelTracesRoute,
  ApiEmbedsApiIframeRoute: ApiEmbedsApiIframeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { startInstance } from './start.ts';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
