#!/usr/bin/env bash
# sync-gstack.sh — vendor the user's local gstack install into this repo.
#
# Pulls source from $HOME/.claude/skills/gstack/ into ./.claude/skills/gstack/,
# excluding platform-specific binaries (bun-compiled for the host's arch),
# install caches, and per-user state. The container rebuilds the linux
# binaries on first sandbox start (see .sandcastle/main.ts and Dockerfile).
#
# Run from the repo root:  bash .sandcastle/scripts/sync-gstack.sh
#
# Re-run any time you want to pull in upstream gstack updates from the host.

set -euo pipefail

SRC="${GSTACK_SRC:-$HOME/.claude/skills/gstack}"
DEST="$(git rev-parse --show-toplevel)/.claude/skills/gstack"

if [ ! -d "$SRC" ]; then
  echo "error: gstack source not found at $SRC" >&2
  echo "       set GSTACK_SRC to override, or install gstack first." >&2
  exit 1
fi

echo "Vendoring gstack:"
echo "  from: $SRC"
echo "  to:   $DEST"

mkdir -p "$DEST"

# rsync excludes:
#   - dist/ everywhere (bun-compiled host binaries)
#   - node_modules/ (regenerated by `bun install` in the container)
#   - .git/ (history is upstream's, not ours)
#   - bun.lock (regenerated)
#   - bin/gstack-global-discover (compiled bun binary; .ts source kept)
#   - per-user state files that bleed into the skills tree
rsync -a --delete \
  --exclude='dist/' \
  --exclude='node_modules/' \
  --exclude='.git/' \
  --exclude='bun.lock' \
  --exclude='bin/gstack-global-discover' \
  --exclude='.feature-prompted-*' \
  --exclude='.completeness-intro-seen' \
  --exclude='.telemetry-prompted' \
  --exclude='.proactive-prompted' \
  --exclude='.routing-declined' \
  --exclude='.vendoring-warned-*' \
  "$SRC/" "$DEST/"

echo "Done. Vendored to $DEST"
echo "Size: $(du -sh "$DEST" | awk '{print $1}')"
