import type { ProposalTemplateSchema, XFormatPropertySchema } from './types';

/**
 * Backwards-compat shim for proposal templates that store a `budget` field as
 * a plain `{ type: 'number', maximum: X }` instead of the canonical money
 * object shape.
 *
 * Legacy templates were generated by CreateDecisionProcessModal (simple.ts,
 * cowop.ts, horizon.ts) before the canonical `x-format: 'money'` shape was
 * adopted. The validator and renderer now both speak the canonical shape, so
 * we rewrite the legacy form on read.
 *
 * Looking forward: `x-format` is the discriminator for the *kind* of budget
 * (money, hours, points, etc.). Today only `'money'` exists, but adding new
 * kinds is additive — drop a new case here when a new kind ships, and the
 * rest of the pipeline already routes on `x-format`.
 *
 * @returns a new template with the budget property canonicalized, or the
 *   original template unchanged when no rewrite is needed.
 */
export function normalizeProposalTemplate(
  template: ProposalTemplateSchema,
): ProposalTemplateSchema {
  const budget = template.properties?.budget;

  if (!isLegacyNumericBudget(budget)) {
    return template;
  }

  return {
    ...template,
    properties: {
      ...template.properties,
      budget: canonicalizeNumericBudget(budget),
    },
  };
}

function isLegacyNumericBudget(
  schema: XFormatPropertySchema | undefined,
): schema is XFormatPropertySchema {
  return (
    typeof schema === 'object' &&
    schema !== null &&
    schema['x-format'] === undefined &&
    schema.type === 'number'
  );
}

function canonicalizeNumericBudget(
  legacy: XFormatPropertySchema,
): XFormatPropertySchema {
  const {
    type: _type,
    maximum,
    minimum,
    default: defaultValue,
    title,
    description,
    ...rest
  } = legacy;

  const amountSchema: XFormatPropertySchema = {
    type: 'number',
    ...(maximum !== undefined ? { maximum } : {}),
    ...(minimum !== undefined ? { minimum } : {}),
    ...(defaultValue !== undefined ? { default: defaultValue } : {}),
  };

  return {
    ...rest,
    type: 'object',
    'x-format': 'money',
    title: title ?? 'Budget',
    ...(description !== undefined ? { description } : {}),
    properties: {
      amount: amountSchema,
      currency: { type: 'string', default: 'USD' },
    },
    required: ['amount'],
  };
}
