/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as SplatRouteImport } from './routes/$';
import { Route as rootRouteImport } from './routes/__root';
import { Route as ApiV1ModerationWebhooksRouteImport } from './routes/api/v1/moderation/webhooks';
import { Route as ApiV1NotificationsTwilioStatusRouteImport } from './routes/api/v1/notifications/twilio/status';
import { Route as ApiV1TrpcTrpcRouteImport } from './routes/api/v1/trpc/$trpc';
import { Route as ApiV1WorkflowsRouteImport } from './routes/api/v1/workflows';
import { Route as IndexRouteImport } from './routes/index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1WorkflowsRoute = ApiV1WorkflowsRouteImport.update({
  id: '/api/v1/workflows',
  path: '/api/v1/workflows',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1ModerationWebhooksRoute = ApiV1ModerationWebhooksRouteImport.update({
  id: '/api/v1/moderation/webhooks',
  path: '/api/v1/moderation/webhooks',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1TrpcTrpcRoute = ApiV1TrpcTrpcRouteImport.update({
  id: '/api/v1/trpc/$trpc',
  path: '/api/v1/trpc/$trpc',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1NotificationsTwilioStatusRoute =
  ApiV1NotificationsTwilioStatusRouteImport.update({
    id: '/api/v1/notifications/twilio/status',
    path: '/api/v1/notifications/twilio/status',
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/api/v1/workflows': typeof ApiV1WorkflowsRoute;
  '/api/v1/moderation/webhooks': typeof ApiV1ModerationWebhooksRoute;
  '/api/v1/trpc/$trpc': typeof ApiV1TrpcTrpcRoute;
  '/api/v1/notifications/twilio/status': typeof ApiV1NotificationsTwilioStatusRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/api/v1/workflows': typeof ApiV1WorkflowsRoute;
  '/api/v1/moderation/webhooks': typeof ApiV1ModerationWebhooksRoute;
  '/api/v1/trpc/$trpc': typeof ApiV1TrpcTrpcRoute;
  '/api/v1/notifications/twilio/status': typeof ApiV1NotificationsTwilioStatusRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/api/v1/workflows': typeof ApiV1WorkflowsRoute;
  '/api/v1/moderation/webhooks': typeof ApiV1ModerationWebhooksRoute;
  '/api/v1/trpc/$trpc': typeof ApiV1TrpcTrpcRoute;
  '/api/v1/notifications/twilio/status': typeof ApiV1NotificationsTwilioStatusRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/$'
    | '/api/v1/workflows'
    | '/api/v1/moderation/webhooks'
    | '/api/v1/trpc/$trpc'
    | '/api/v1/notifications/twilio/status';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/$'
    | '/api/v1/workflows'
    | '/api/v1/moderation/webhooks'
    | '/api/v1/trpc/$trpc'
    | '/api/v1/notifications/twilio/status';
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/v1/workflows'
    | '/api/v1/moderation/webhooks'
    | '/api/v1/trpc/$trpc'
    | '/api/v1/notifications/twilio/status';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  ApiV1WorkflowsRoute: typeof ApiV1WorkflowsRoute;
  ApiV1ModerationWebhooksRoute: typeof ApiV1ModerationWebhooksRoute;
  ApiV1TrpcTrpcRoute: typeof ApiV1TrpcTrpcRoute;
  ApiV1NotificationsTwilioStatusRoute: typeof ApiV1NotificationsTwilioStatusRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$': {
      id: '/$';
      path: '/$';
      fullPath: '/$';
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/v1/workflows': {
      id: '/api/v1/workflows';
      path: '/api/v1/workflows';
      fullPath: '/api/v1/workflows';
      preLoaderRoute: typeof ApiV1WorkflowsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/v1/moderation/webhooks': {
      id: '/api/v1/moderation/webhooks';
      path: '/api/v1/moderation/webhooks';
      fullPath: '/api/v1/moderation/webhooks';
      preLoaderRoute: typeof ApiV1ModerationWebhooksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/v1/trpc/$trpc': {
      id: '/api/v1/trpc/$trpc';
      path: '/api/v1/trpc/$trpc';
      fullPath: '/api/v1/trpc/$trpc';
      preLoaderRoute: typeof ApiV1TrpcTrpcRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/v1/notifications/twilio/status': {
      id: '/api/v1/notifications/twilio/status';
      path: '/api/v1/notifications/twilio/status';
      fullPath: '/api/v1/notifications/twilio/status';
      preLoaderRoute: typeof ApiV1NotificationsTwilioStatusRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiV1WorkflowsRoute: ApiV1WorkflowsRoute,
  ApiV1ModerationWebhooksRoute: ApiV1ModerationWebhooksRoute,
  ApiV1TrpcTrpcRoute: ApiV1TrpcTrpcRoute,
  ApiV1NotificationsTwilioStatusRoute: ApiV1NotificationsTwilioStatusRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { startInstance } from './start.ts';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
