#!/usr/bin/env bash
# Write a dotenv file from a committed 1Password template, so credentials live
# in 1Password instead of in a file passed around out of band.
#
#   pnpm env:pull                # env/local.env.tpl   -> .env.local
#   pnpm env:pull staging        # env/staging.env.tpl -> .env.staging
#   pnpm env:pull staging --out .env.staging.readonly
#
# Templates hold `op://<vault>/<item>/<field>` references, never secrets;
# `op inject` resolves them. In CI, set OP_SERVICE_ACCOUNT_TOKEN and the same
# command runs unattended.
#
# Idempotent: re-run it whenever a credential rotates.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE_DIR="$REPO_ROOT/env"
GENERATED_MARKER='# Generated by scripts/op-env.sh'

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() {
  printf '\033[1;31m!!\033[0m %s\n' "$*" >&2
  exit 1
}

available_environments() {
  local template names=()
  for template in "$TEMPLATE_DIR"/*.env.tpl; do
    [[ -f "$template" ]] || continue
    names+=("$(basename "$template" .env.tpl)")
  done
  # ${names[*]:-} rather than ${names[*]}: an empty array is "unbound" under
  # `set -u` on the bash 3.2 that ships with macOS.
  echo "${names[*]:-}"
}

usage() {
  cat <<EOF
Usage: pnpm env:pull [environment] [--out <path>] [--force]

Resolves env/<environment>.env.tpl through 1Password and writes the result.

  environment   Defaults to 'local'. Available: $(available_environments)
  --out <path>  Output path. Defaults to .env.local for 'local',
                .env.<environment> otherwise.
  --force       Overwrite an output file this script did not generate.

Authentication: sign in to the 1Password app with the CLI integration enabled,
or set OP_SERVICE_ACCOUNT_TOKEN (CI).
EOF
}

ENVIRONMENT=""
OUT=""
FORCE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h | --help)
      usage
      exit 0
      ;;
    --force)
      FORCE=true
      shift
      ;;
    --out)
      [[ $# -ge 2 ]] || die "--out needs a path."
      OUT="$2"
      shift 2
      ;;
    -*)
      usage >&2
      die "Unknown option: $1"
      ;;
    *)
      [[ -z "$ENVIRONMENT" ]] || die "Only one environment at a time (got '$ENVIRONMENT' and '$1')."
      ENVIRONMENT="$1"
      shift
      ;;
  esac
done

ENVIRONMENT="${ENVIRONMENT:-local}"
TEMPLATE="$TEMPLATE_DIR/$ENVIRONMENT.env.tpl"

if [[ ! -f "$TEMPLATE" ]]; then
  die "No template for '$ENVIRONMENT'. Available: $(available_environments)"
fi

if [[ -z "$OUT" ]]; then
  if [[ "$ENVIRONMENT" == "local" ]]; then
    OUT="$REPO_ROOT/.env.local"
  else
    OUT="$REPO_ROOT/.env.$ENVIRONMENT"
  fi
fi

OUT_DIR="$(dirname "$OUT")"
[[ -d "$OUT_DIR" ]] || die "Output directory does not exist: $OUT_DIR"

# --- Preflight ---------------------------------------------------------------
if ! command -v op >/dev/null; then
  die "The 1Password CLI is not installed.
  macOS:  brew install --cask 1password-cli
  Linux:  https://developer.1password.com/docs/cli/get-started/"
fi

if ! op whoami >/dev/null 2>&1; then
  if [[ -n "${OP_SERVICE_ACCOUNT_TOKEN:-}" ]]; then
    die "OP_SERVICE_ACCOUNT_TOKEN is set but 1Password rejected it. Check that the
  token has not expired and that its service account can read the 'Common' vault."
  fi
  die "Not signed in to 1Password. Either:
  - open the 1Password app and turn on Settings > Developer > 'Integrate with 1Password CLI', or
  - run: eval \$(op signin)
  In CI, set OP_SERVICE_ACCOUNT_TOKEN instead."
fi

# --- Don't clobber a hand-written file ---------------------------------------
# Every file this script writes starts with GENERATED_MARKER, so anything
# without it is someone's own env file and needs an explicit --force.
if [[ "$FORCE" != true && -e "$OUT" ]] && ! head -n 1 "$OUT" | grep -qF "$GENERATED_MARKER"; then
  die "$OUT already exists and was not generated by this script.
  Move it aside, or re-run with --force to overwrite it."
fi

# --- Resolve ------------------------------------------------------------------
TEMPLATE_REL="${TEMPLATE#"$REPO_ROOT"/}"
TMP="$(mktemp "$OUT.XXXXXX")"
# shellcheck disable=SC2064 # $TMP is fixed at trap time on purpose.
trap "rm -f '$TMP'" EXIT

log "Resolving $TEMPLATE_REL through 1Password…"
if ! {
  printf '%s from %s. Do not edit.\n' "$GENERATED_MARKER" "$TEMPLATE_REL"
  printf '# Re-run `pnpm env:pull %s` to refresh; change what is pulled in the template.\n\n' "$ENVIRONMENT"
  op inject --in-file "$TEMPLATE"
} >"$TMP"; then
  die "1Password could not resolve every reference in $TEMPLATE_REL (see the error above).
  A missing item or field fails the whole pull, so $OUT was left untouched.
  Check that each op:// reference in the template exists in the vault."
fi

chmod 600 "$TMP"
mv "$TMP" "$OUT"
trap - EXIT

log "Wrote ${OUT#"$REPO_ROOT"/}"
